import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image

# ==========================================
# PAGE CONFIGURATION
# ==========================================
st.set_page_config(
    page_title="Real vs AI Image Detector",
    page_icon="🔍",
    layout="centered"
)

# ==========================================
# MODEL LOADING (Cached for speed)
# ==========================================
@st.cache_resource
def load_detector_model():
    try:
        # Load the model saved from the training script
        model = tf.keras.models.load_model("ai_detector_model.keras", compile=False)
        return model
    except Exception as e:
        st.error(f"Failed to load model. Ensure 'ai_detector_model.keras' is in the same directory.\nError: {e}")
        return None

# ==========================================
# PREPROCESSING (Must match training exactly)
# ==========================================
def preprocess_image(image):
    """Resizes and applies the High-Pass Frequency Filter used in training."""
    # Resize to EfficientNet standard
    img = image.resize((224, 224))
    img_array = np.array(img)
    
    # Add batch dimension -> (1, 224, 224, 3)
    img_tensor = tf.convert_to_tensor(img_array, dtype=tf.float32)
    img_tensor = tf.expand_dims(img_tensor, 0)
    
    # Apply FFT high-pass filter
    img_complex = tf.cast(img_tensor, tf.complex64)
    img_t = tf.transpose(img_complex, [0, 3, 1, 2])
    
    fft = tf.signal.fft2d(img_t)
    fft_shift = tf.signal.fftshift(fft, axes=[2, 3])
    
    h, w = 224, 224
    center_y, center_x = tf.cast(h // 2, tf.float32), tf.cast(w // 2, tf.float32)
    radius = 15.0 
    
    y, x = tf.meshgrid(tf.range(tf.cast(h, tf.float32)), tf.range(tf.cast(w, tf.float32)), indexing='ij')
    dist = tf.sqrt(tf.square(x - center_x) + tf.square(y - center_y))
    mask = dist > radius
    mask = tf.cast(mask, tf.complex64)
    mask = tf.expand_dims(tf.expand_dims(mask, 0), 0)
    
    fft_shift = fft_shift * mask
    ifft = tf.signal.ifft2d(tf.signal.ifftshift(fft_shift, axes=[2, 3]))
    
    high_freq_img = tf.abs(tf.transpose(ifft, [0, 2, 3, 1]))
    
    image_blended = img_tensor + (high_freq_img * 0.1)
    image_blended = tf.clip_by_value(image_blended, 0.0, 255.0)
    
    return image_blended

# ==========================================
# MAIN UI LAYOUT
# ==========================================
st.title("🔍 AI Image Detector")
st.write("Upload an image to determine if it was captured by a camera or generated by Artificial Intelligence.")

# Load Model
model = load_detector_model()

if model:
    # File Uploader
    uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png", "webp"])

    if uploaded_file is not None:
        # Display the uploaded image
        image = Image.open(uploaded_file).convert('RGB')
        st.image(image, caption='Uploaded Image', use_container_width=True)
        
        # Analyze Button
        if st.button("Analyze Image", type="primary"):
            with st.spinner('Analyzing pixel frequencies and artifacts...'):
                
                # Preprocess and Predict
                processed_tensor = preprocess_image(image)
                prediction = model.predict(processed_tensor)[0][0]
                
                # Calculate Confidence
                # Assuming standard alphabetical dataset loading: 0 = Fake, 1 = Real
                if prediction >= 0.5:
                    result = "REAL"
                    confidence = prediction * 100
                    color = "green"
                else:
                    result = "FAKE (AI Generated)"
                    confidence = (1 - prediction) * 100
                    color = "red"
                
                # Display Results
                st.markdown("---")
                st.subheader("Analysis Complete")
                
                # Use Markdown to display colored text
                st.markdown(f"<h2 style='text-align: center; color: {color};'>{result}</h2>", unsafe_allow_html=True)
                
                # Display Confidence Metrics
                st.write(f"**Confidence Score:** {confidence:.2f}%")
                st.progress(int(confidence))
                
                # Educational breakdown
                with st.expander("How does this work?"):
                    st.write("""
                    This model uses **EfficientNetB0** to analyze the image. 
                    Before analyzing, it applies a **Fast Fourier Transform (FFT) High-Pass Filter** to the image. 
                    AI generators (like Midjourney or DALL-E) often leave microscopic, high-frequency noise patterns in the pixels that human eyes cannot see. 
                    The filter exposes these hidden patterns so the AI can catch the fakes.
                    """)